export const GET_SAVED_MONEY_REQUEST = 'GET_SAVED_MONEY_REQUEST'
export const GET_SAVED_MONEY_SUCCESS = 'GET_SAVED_MONEY_SUCCESS'
export const GET_SAVED_MONEY_FAILURE = 'GET_SAVED_MONEY_FAILURE'

export const ADD_MONEY_REQUEST = 'ADD_MONEY_REQUEST'
export const ADD_MONEY_SUCCESS = 'ADD_MONEY_SUCCESS'
export const ADD_MONEY_FAILURE = 'ADD_MONEY_FAILURE'

export const DELETE_MONEY_REQUEST = 'DELETE_MONEY_REQUEST'
export const DELETE_MONEY_SUCCESS = 'DELETE_MONEY_SUCCESS'
export const DELETE_MONEY_FAILURE = 'REMOVE_MONEY_FAILURE'

export const GET_TOTAL_REQUEST = 'GET_TOTAL_REQUEST'
export const GET_TOTAL_SUCCESS = 'GET_TOTAL_SUCCESS'
export const GET_TOTAL_FAILURE = 'GET_TOTAL_FAILURE'

export const DEPOSIT_MONEY_REQUEST = 'DEPOSIT_MONEY_REQUEST'
export const DEPOSIT_MONEY_SUCCESS = 'DEPOSIT_MONEY_SUCCESS'
export const DEPOSIT_MONEY_FAILURE = 'DEPOSIT_MONEY_FAILURE'

export const DEBT_MONEY_REQUEST = 'DEBT_MONEY_REQUEST'
export const DEBT_MONEY_SUCCESS = 'DEBT_MONEY_SUCCESS'
export const DEBT_MONEY_FAILURE = 'DEBT_MONEY_FAILURE'

export const ADD_TO_WISHLIST_REQUEST = 'ADD_WISHLIST_REQUEST'
export const ADD_TO_WISHLIST_SUCCESS = 'ADD_WISHLIST_SUCCESS'
export const ADD_TO_WISHLIST_FAILURE = 'ADD_WISHLIST_FAILURE'

export const GET_WISHLIST_REQUEST = 'GET_WISHLIST_REQUEST'
export const GET_WISHLIST_SUCCESS = 'GET_WISHLIST_SUCCESS'
export const GET_WISHLIST_FAILURE = 'GET_WISHLIST_FAILURE'
