export const GET_SAVED_MONEY_REQUEST = 'GET_SAVED_MONEY_REQUEST'
export const GET_SAVED_MONEY_SUCCESS = 'GET_SAVED_MONEY_SUCCESS'
export const GET_SAVED_MONEY_FAILURE = 'GET_SAVED_MONEY_FAILURE'

export const ADD_MONEY_REQUEST = 'ADD_MONEY_REQUEST'
export const ADD_MONEY_SUCCESS = 'ADD_MONEY_SUCCESS'
export const ADD_MONEY_FAILURE = 'ADD_MONEY_FAILURE'

export const REMOVE_MONEY_REQUEST = 'REMOVE_MONEY_REQUEST'
export const REMOVE_MONEY_SUCCESS = 'REMOVE_MONEY_SUCCESS'
export const REMOVE_MONEY_FAILURE = 'REMOVE_MONEY_FAILURE'

export const EDIT_MONEY_REQUEST = 'EDIT_MONEY_REQUEST'
export const EDIT_MONEY_SUCCESS = 'EDIT_MONEY_SUCCESS'
export const EDIT_MONEY_FAILURE = 'EDIT_MONEY_FAILURE'
